server:
  port: 8080
zuul:
  routes:
    one:
      path: /nacosclient/**
      serviceId: nacosclient
      #url: http://localhost:8888/baoban/
  prefix: /nacos
spring:
  application:
    name: sentinelzuul
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER:localhost:8848}
