server:
  port: 8080
zuul:
  routes:
    one:
      path: /baoban/**
      url: http://localhost:8888/baoban/
spring:
  application:
    name: sentinelzuul
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER:localhost:8848}
